### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yunjae2** [yunjae2/latte#2]
- [ ] User-configurable default run parameters (rps, duration, etc.)
- [x] Show currently running test to any client
- [ ] Advanced run parameters (expected latencies)
- [x] Modifiable test name
- [x] README
- [x] Browsable input for run parameters (branch, script file)
- [x] Stopping a running test
- [x] Option for clearing last result from cache (settings)
- [x] Limit the size of the last result cache
- [ ] Floating-point RPS
- [ ] Script validation
- [x] Maintain previous logs
- [ ] Graphical visualization of test runtime stats 
- [x] #10
- [x] #9
- [ ] #12
- [ ] History search
- [ ] Exclude setup_data from the summary

**Comment by yunjae2** [comment]
Deployment
- [ ] Dockerize the application

**Comment by dain7672** [comment]
wonderful

**Comment by yunjae2** [comment]
> wonderful

Thanks! haha
